- name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bikbotclient
          # This tells it to search EVERY folder for any .dll it created
          path: |
            bin/**/*.dll
            x64/**/*.dll
            out/**/*.dll
            ./*.dll
