name: Build BikBot
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet Packages
        run: nuget restore

      - name: Build
        run: msbuild /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bikbotclient
          path: "**/*.dll"
